name: nyx_converter
version: 0.4.0
description: >-
  A Flutter package that makes it easier to convert formats, codecs, etc. of media files.
repository: https://github.com/xaus-group/nyx_converter
issue_tracker: https://github.com/xaus-group/nyx_converter/issues
# homepage:
documentation: https://pub.dev/documentation/nyx_converter/latest
topics: [video, audio, converter, ffmpeg]

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=3.27.3'

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_new: ^3.2.0
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

assets:
  - assets/videos/

screenshots:
  - description: The flutter nyx_converter package logo.
    path: screenshots/logo.png
